# Generated by Django 3.1.6 on 2021-04-02 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('social', '0007_auto_20210402_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_dislike',
            new_name='reply_dislikes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply_like',
            new_name='reply_likes',
        ),
    ]
