# Generated by Django 3.1.6 on 2021-04-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/post_photos'),
        ),
    ]
