# Generated by Django 3.1.6 on 2021-04-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threadmodel',
            old_name='users',
            new_name='user',
        ),
    ]
